<?php

namespace Database\Seeders;

use App\Models\Member;
use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            [
                'title'             => 'Pastor',
                'first_name'        => 'James',
                'last_name'         => 'Adeyemi',
                'email'             => 'james.adeyemi@example.com',
                'phone'             => '07700 900001',
                'date_of_birth'     => '1975-03-15',
                'gender'            => 'male',
                'marital_status'    => 'married',
                'occupation'        => 'Senior Pastor',
                'address'           => '12 Church Lane',
                'city'              => 'London',
                'postcode'          => 'E1 6AN',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2005-01-09',
                'membership_date'   => '2005-03-20',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '1993-06-12',
            ],
            [
                'title'             => 'Mrs',
                'first_name'        => 'Grace',
                'last_name'         => 'Adeyemi',
                'email'             => 'grace.adeyemi@example.com',
                'phone'             => '07700 900002',
                'date_of_birth'     => '1978-07-22',
                'gender'            => 'female',
                'marital_status'    => 'married',
                'occupation'        => 'Teacher',
                'address'           => '12 Church Lane',
                'city'              => 'London',
                'postcode'          => 'E1 6AN',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2005-01-09',
                'membership_date'   => '2005-03-20',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '1996-09-08',
            ],
            [
                'title'             => 'Mr',
                'first_name'        => 'Daniel',
                'last_name'         => 'Okonkwo',
                'email'             => 'daniel.okonkwo@example.com',
                'phone'             => '07700 900003',
                'date_of_birth'     => '1990-11-05',
                'gender'            => 'male',
                'marital_status'    => 'single',
                'occupation'        => 'Software Engineer',
                'address'           => '45 Victoria Road',
                'city'              => 'Manchester',
                'postcode'          => 'M1 2EQ',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2018-04-15',
                'membership_date'   => '2018-09-01',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2018-12-09',
            ],
            [
                'title'             => 'Mrs',
                'first_name'        => 'Esther',
                'last_name'         => 'Williams',
                'email'             => 'esther.williams@example.com',
                'phone'             => '07700 900004',
                'date_of_birth'     => '1985-02-14',
                'gender'            => 'female',
                'marital_status'    => 'married',
                'occupation'        => 'Nurse',
                'address'           => '8 Maple Street',
                'city'              => 'Birmingham',
                'postcode'          => 'B1 1BB',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2015-06-21',
                'membership_date'   => '2015-11-15',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2016-04-03',
            ],
            [
                'title'             => 'Mr',
                'first_name'        => 'Samuel',
                'last_name'         => 'Mensah',
                'email'             => 'samuel.mensah@example.com',
                'phone'             => '07700 900005',
                'date_of_birth'     => '1988-09-30',
                'gender'            => 'male',
                'marital_status'    => 'married',
                'occupation'        => 'Accountant',
                'address'           => '22 Kings Road',
                'city'              => 'Leeds',
                'postcode'          => 'LS1 3AD',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2012-01-08',
                'membership_date'   => '2012-06-10',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2012-09-16',
            ],
            [
                'title'             => 'Miss',
                'first_name'        => 'Ruth',
                'last_name'         => 'Nkemelu',
                'email'             => 'ruth.nkemelu@example.com',
                'phone'             => '07700 900006',
                'date_of_birth'     => '1995-12-01',
                'gender'            => 'female',
                'marital_status'    => 'single',
                'occupation'        => 'Graphic Designer',
                'address'           => '3 Elm Avenue',
                'city'              => 'London',
                'postcode'          => 'SE15 4QS',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2020-02-16',
                'membership_date'   => '2020-07-12',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2020-11-22',
            ],
            [
                'title'             => 'Mr',
                'first_name'        => 'Emmanuel',
                'last_name'         => 'Owusu',
                'email'             => 'emmanuel.owusu@example.com',
                'phone'             => '07700 900007',
                'date_of_birth'     => '1982-05-19',
                'gender'            => 'male',
                'marital_status'    => 'married',
                'occupation'        => 'Civil Engineer',
                'address'           => '17 Park Crescent',
                'city'              => 'Bristol',
                'postcode'          => 'BS1 5NB',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2010-09-05',
                'membership_date'   => '2011-01-16',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2011-05-29',
            ],
            [
                'title'             => 'Mrs',
                'first_name'        => 'Abigail',
                'last_name'         => 'Owusu',
                'email'             => 'abigail.owusu@example.com',
                'phone'             => '07700 900008',
                'date_of_birth'     => '1984-08-25',
                'gender'            => 'female',
                'marital_status'    => 'married',
                'occupation'        => 'Pharmacist',
                'address'           => '17 Park Crescent',
                'city'              => 'Bristol',
                'postcode'          => 'BS1 5NB',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2010-09-05',
                'membership_date'   => '2011-01-16',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2003-07-20',
            ],
            [
                'title'             => null,
                'first_name'        => 'David',
                'last_name'         => 'Thompson',
                'email'             => 'david.thompson@example.com',
                'phone'             => '07700 900009',
                'date_of_birth'     => '2000-04-10',
                'gender'            => 'male',
                'marital_status'    => 'single',
                'occupation'        => 'University Student',
                'address'           => '56 High Street',
                'city'              => 'London',
                'postcode'          => 'N1 0QH',
                'country'           => 'United Kingdom',
                'membership_status' => 'new_convert',
                'first_visit_date'  => '2025-11-03',
                'membership_date'   => null,
                'baptism_status'    => 'not_baptised',
                'baptism_date'      => null,
            ],
            [
                'title'             => 'Ms',
                'first_name'        => 'Priscilla',
                'last_name'         => 'Asante',
                'email'             => 'priscilla.asante@example.com',
                'phone'             => '07700 900010',
                'date_of_birth'     => '1992-06-18',
                'gender'            => 'female',
                'marital_status'    => 'single',
                'occupation'        => 'Marketing Manager',
                'address'           => '9 Orchard Way',
                'city'              => 'London',
                'postcode'          => 'SW11 3PL',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2017-03-12',
                'membership_date'   => '2017-08-20',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2017-12-10',
            ],
            [
                'title'             => null,
                'first_name'        => 'Michael',
                'last_name'         => 'Johnson',
                'email'             => 'michael.johnson@example.com',
                'phone'             => '07700 900011',
                'date_of_birth'     => '1998-01-27',
                'gender'            => 'male',
                'marital_status'    => 'single',
                'occupation'        => 'Barista',
                'address'           => '31 Station Road',
                'city'              => 'London',
                'postcode'          => 'E8 1DY',
                'country'           => 'United Kingdom',
                'membership_status' => 'visitor',
                'first_visit_date'  => '2026-03-02',
                'membership_date'   => null,
                'baptism_status'    => null,
                'baptism_date'      => null,
            ],
            [
                'title'             => 'Deacon',
                'first_name'        => 'Joseph',
                'last_name'         => 'Appiah',
                'email'             => 'joseph.appiah@example.com',
                'phone'             => '07700 900012',
                'date_of_birth'     => '1970-10-03',
                'gender'            => 'male',
                'marital_status'    => 'married',
                'occupation'        => 'Retired Teacher',
                'address'           => '4 Meadow Lane',
                'city'              => 'Wolverhampton',
                'postcode'          => 'WV1 1ES',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2008-05-18',
                'membership_date'   => '2008-10-05',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '1990-08-15',
            ],
            [
                'title'             => 'Deaconess',
                'first_name'        => 'Florence',
                'last_name'         => 'Appiah',
                'email'             => 'florence.appiah@example.com',
                'phone'             => '07700 900013',
                'date_of_birth'     => '1972-03-21',
                'gender'            => 'female',
                'marital_status'    => 'married',
                'occupation'        => 'Social Worker',
                'address'           => '4 Meadow Lane',
                'city'              => 'Wolverhampton',
                'postcode'          => 'WV1 1ES',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2008-05-18',
                'membership_date'   => '2008-10-05',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '1992-04-19',
            ],
            [
                'title'             => 'Mr',
                'first_name'        => 'Benjamin',
                'last_name'         => 'Eze',
                'email'             => 'benjamin.eze@example.com',
                'phone'             => '07700 900014',
                'date_of_birth'     => '1993-07-08',
                'gender'            => 'male',
                'marital_status'    => 'single',
                'occupation'        => 'Data Analyst',
                'address'           => '60 Queen Street',
                'city'              => 'London',
                'postcode'          => 'EC4N 1SP',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2019-08-11',
                'membership_date'   => '2020-01-19',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2020-06-14',
            ],
            [
                'title'             => 'Mrs',
                'first_name'        => 'Mercy',
                'last_name'         => 'Boateng',
                'email'             => 'mercy.boateng@example.com',
                'phone'             => '07700 900015',
                'date_of_birth'     => '1987-11-14',
                'gender'            => 'female',
                'marital_status'    => 'widowed',
                'occupation'        => 'Catering Manager',
                'address'           => '25 Riverside Drive',
                'city'              => 'London',
                'postcode'          => 'SE10 0QJ',
                'country'           => 'United Kingdom',
                'membership_status' => 'member',
                'first_visit_date'  => '2014-02-23',
                'membership_date'   => '2014-07-13',
                'baptism_status'    => 'baptised',
                'baptism_date'      => '2006-03-26',
            ],
        ];

        foreach ($members as $data) {
            Member::create(array_merge($data, ['is_active' => true]));
        }

        // Link spouses
        $james = Member::where('email', 'james.adeyemi@example.com')->first();
        $grace = Member::where('email', 'grace.adeyemi@example.com')->first();
        if ($james && $grace) {
            $james->update(['is_spouse_member' => true, 'spouse_id' => $grace->id]);
            $grace->update(['is_spouse_member' => true, 'spouse_id' => $james->id]);
        }

        $emmanuel = Member::where('email', 'emmanuel.owusu@example.com')->first();
        $abigail = Member::where('email', 'abigail.owusu@example.com')->first();
        if ($emmanuel && $abigail) {
            $emmanuel->update(['is_spouse_member' => true, 'spouse_id' => $abigail->id]);
            $abigail->update(['is_spouse_member' => true, 'spouse_id' => $emmanuel->id]);
        }

        $joseph = Member::where('email', 'joseph.appiah@example.com')->first();
        $florence = Member::where('email', 'florence.appiah@example.com')->first();
        if ($joseph && $florence) {
            $joseph->update(['is_spouse_member' => true, 'spouse_id' => $florence->id]);
            $florence->update(['is_spouse_member' => true, 'spouse_id' => $joseph->id]);
        }
    }
}
