<?php

namespace Database\Seeders;

use App\Models\Ministry;
use Illuminate\Database\Seeder;

class MinistrySeeder extends Seeder
{
    public function run(): void
    {
        $ministries = [
            [
                'name' => 'Worship & Arts',
                'slug' => 'worship',
                'subtitle' => 'Music · Creative Arts',
                'description' => 'Experience the presence of God through Spirit-filled praise and worship every Sunday.',
                'about_text' => "Our Worship & Arts ministry exists to create an atmosphere where people can encounter God through music, song, and creative expression.\n\nWhether you sing, play an instrument, or serve behind the scenes with sound and visuals, there is a place for you to use your gifts for God's glory.",
                'vision_quote' => 'Let everything that has breath praise the Lord.',
                'image_path' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=900&q=80',
                'category_label' => 'Music',
                'meeting_schedule' => 'Sundays · 8:30 AM (Rehearsal)',
                'location' => 'Main Auditorium',
                'leader_name' => 'Minister Grace Okonkwo',
                'leader_role' => 'Worship Director',
                'sort_order' => 0,
            ],
            [
                'name' => 'Community Groups',
                'slug' => 'community-groups',
                'subtitle' => 'Life Together',
                'description' => 'Connect with others in small groups designed to grow together in faith.',
                'about_text' => "Community Groups are the heartbeat of our church family. These weekly gatherings are where real life happens — sharing meals, studying the Word, praying for one another, and building lasting friendships.\n\nGroups meet across Sheffield in homes and community spaces. Whether you're new to faith or have walked with Jesus for years, there's a group for you.",
                'vision_quote' => 'They broke bread in their homes and ate together with glad and sincere hearts.',
                'image_path' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900&q=80',
                'category_label' => 'Fellowship',
                'meeting_schedule' => 'Wednesdays · 7:00 PM',
                'location' => 'Various Locations',
                'leader_name' => 'Pastor James & Sarah Mitchell',
                'leader_role' => 'Groups Coordinators',
                'sort_order' => 1,
            ],
            [
                'name' => 'Missions & Outreach',
                'slug' => 'missions',
                'subtitle' => 'Local & Global',
                'description' => 'We partner with missionaries globally to spread the Gospel to the ends of the earth.',
                'about_text' => "Our Missions & Outreach ministry is committed to taking the love of Christ beyond our walls. We support mission partners across multiple countries and run local initiatives that serve the most vulnerable in our city.\n\nFrom food banks and clothing drives to overseas mission trips, we believe every believer is called to be a witness wherever they are.",
                'vision_quote' => 'Go and make disciples of all nations.',
                'image_path' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=900&q=80',
                'category_label' => 'Outreach',
                'meeting_schedule' => '1st Saturday · 10:00 AM',
                'location' => 'Community Hall',
                'leader_name' => 'Deacon Thomas Adeyemi',
                'leader_role' => 'Missions Lead',
                'sort_order' => 2,
            ],
            [
                'name' => 'Community Outreach',
                'slug' => 'outreach',
                'subtitle' => 'Serving Sheffield',
                'description' => 'Serving our city with love and compassion through local outreach initiatives.',
                'about_text' => "Community Outreach is how we put our faith into action right here in Sheffield. We run regular programmes including a food pantry, after-school mentoring, and support for the elderly and isolated.\n\nWe believe the local church should be the best news in every neighbourhood. Join us as we serve with compassion and share the hope of Jesus.",
                'vision_quote' => 'Faith without works is dead.',
                'image_path' => 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=900&q=80',
                'category_label' => 'Service',
                'meeting_schedule' => 'Saturdays · 9:00 AM',
                'location' => 'City Centre Campus',
                'leader_name' => 'Sister Ruth Kamau',
                'leader_role' => 'Outreach Coordinator',
                'sort_order' => 3,
            ],
            [
                'name' => 'Bible Study',
                'slug' => 'bible-study',
                'subtitle' => 'Digging Deeper',
                'description' => 'Deepen your understanding of Scripture through our weekly study sessions.',
                'about_text' => "Our Bible Study ministry provides a space to dig deeper into God's Word. Each week we explore Scripture together through verse-by-verse teaching, discussion, and practical application.\n\nWhether you are just beginning to read the Bible or have been studying for decades, these sessions will strengthen your faith and equip you for everyday life.",
                'vision_quote' => 'Your word is a lamp to my feet and a light to my path.',
                'image_path' => 'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=900&q=80',
                'category_label' => 'Education',
                'meeting_schedule' => 'Tuesdays · 7:00 PM',
                'location' => 'Room 3, City Centre Campus',
                'leader_name' => 'Elder Michael Osei',
                'leader_role' => 'Teaching Elder',
                'sort_order' => 4,
            ],
            [
                'name' => 'Youth & Kids',
                'slug' => 'youth-and-kids',
                'subtitle' => 'Ages 3 – 18',
                'description' => 'A safe and fun environment for children and teens to discover their faith.',
                'about_text' => "Youth & Kids is a vibrant ministry dedicated to helping the next generation know and follow Jesus. Our programmes are age-appropriate, fun, and rooted in Scripture.\n\nFrom Sunday kids church to Friday night youth sessions, we create safe spaces where young people can ask questions, build friendships, and grow in their walk with God.",
                'vision_quote' => 'Train up a child in the way he should go; even when he is old he will not depart from it.',
                'image_path' => 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=900&q=80',
                'category_label' => 'Youth',
                'meeting_schedule' => 'Sundays · 10:00 AM & Fridays · 6:30 PM',
                'location' => 'Youth Hall',
                'leader_name' => 'Pastor Daniel & Joy Wright',
                'leader_role' => 'Youth & Children\'s Pastors',
                'sort_order' => 5,
            ],
            [
                'name'             => 'Men\'s Ministry',
                'slug'             => 'mens-ministry',
                'subtitle'         => 'Iron Sharpens Iron',
                'description'      => 'Equipping men to lead with integrity, faith, and purpose in every area of life.',
                'about_text'       => "Men's Ministry exists to build men of God who are strong in character, rooted in Scripture, and servant-hearted in their homes, workplaces, and community.\n\nThrough regular fellowship, discipleship, and honest conversation, we equip men to live out the call of God with courage and accountability.",
                'vision_quote'     => 'As iron sharpens iron, so one person sharpens another.',
                'image_path'       => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900&q=80',
                'category_label'   => 'Men',
                'meeting_schedule' => '2nd Saturday · 8:00 AM',
                'location'         => 'Main Hall, City Centre Campus',
                'leader_name'      => 'Deacon Samuel Obi',
                'leader_role'      => 'Men\'s Ministry Lead',
                'sort_order'       => 6,
            ],
            [
                'name'             => 'Women\'s Ministry',
                'slug'             => 'womens-ministry',
                'subtitle'         => 'Crowned with Strength',
                'description'      => 'A sisterhood of women growing, encouraging, and empowering one another in Christ.',
                'about_text'       => "Women's Ministry is a vibrant community of women who support, challenge, and celebrate each other through every season of life.\n\nWe host regular gatherings, Bible studies, and special events designed to deepen faith, foster authentic friendship, and equip women to walk boldly in their God-given identity and calling.",
                'vision_quote'     => 'She is clothed with strength and dignity, and she laughs without fear of the future.',
                'image_path'       => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=900&q=80',
                'category_label'   => 'Women',
                'meeting_schedule' => '3rd Saturday · 10:00 AM',
                'location'         => 'Conference Room, City Centre Campus',
                'leader_name'      => 'Pastor Mrs. Adaeze Nwosu',
                'leader_role'      => 'Women\'s Ministry Lead',
                'sort_order'       => 7,
            ],
            [
                'name'             => 'Prayer Ministry',
                'slug'             => 'prayer',
                'subtitle'         => 'The Engine Room',
                'description'      => 'Covering the church, families, and city through sustained, fervent intercession.',
                'about_text'       => "Prayer is the foundation of everything we do at City Life. The Prayer Ministry gathers believers who are passionate about seeking God together, interceding for our church family, Sheffield, the nation, and the nations.\n\nWe believe prayer changes things. Join us as we stand in the gap and see God move in powerful ways.",
                'vision_quote'     => 'The effective, fervent prayer of a righteous man avails much.',
                'image_path'       => 'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=900&q=80',
                'category_label'   => 'Prayer',
                'meeting_schedule' => 'Tuesdays & Thursdays · 6:00 AM',
                'location'         => 'Prayer Room, City Centre Campus',
                'leader_name'      => 'Elder Emmanuel Asante',
                'leader_role'      => 'Prayer Coordinator',
                'sort_order'       => 8,
            ],
            [
                'name'             => 'Youth Ministry',
                'slug'             => 'youth',
                'subtitle'         => 'Raised for This',
                'description'      => 'Empowering teenagers to discover their identity in Christ and live on fire for God.',
                'about_text'       => "Youth Ministry is a dynamic, Spirit-filled community for teenagers aged 13–18. We believe this generation is not just the future of the church — they are the church right now.\n\nThrough Friday night sessions, youth camps, and discipleship programmes, we create spaces where young people encounter God, build real friendships, and are equipped to impact their schools and communities.",
                'vision_quote'     => 'Don\'t let anyone look down on you because you are young, but set an example in speech, in conduct, in love, in faith and in purity.',
                'image_path'       => 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=900&q=80',
                'category_label'   => 'Youth',
                'meeting_schedule' => 'Fridays · 6:30 PM',
                'location'         => 'Youth Hall',
                'leader_name'      => 'Pastor Daniel Wright',
                'leader_role'      => 'Youth Pastor',
                'sort_order'       => 9,
            ],
        ];

        foreach ($ministries as $data) {
            Ministry::updateOrCreate(
                ['slug' => $data['slug']],
                $data + ['is_active' => true],
            );
        }
    }
}
